# Generated by Django 3.0.4 on 2020-04-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor_app', '0002_client_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='policy_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_id', models.CharField(max_length=100)),
                ('date_of_insurance', models.DateField()),
                ('client_id', models.CharField(max_length=100)),
                ('agent_id', models.CharField(max_length=20)),
            ],
        ),
    ]
