# Generated by Django 3.0.4 on 2020-04-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor_app', '0003_policy_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=100)),
                ('insurance_id', models.CharField(max_length=100)),
                ('date_of_insurance', models.DateField()),
                ('reason', models.CharField(max_length=20)),
            ],
        ),
    ]
