# Generated by Django 3.0.4 on 2020-04-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor_app', '0005_office_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_details',
            name='status',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='client_details',
            name='status',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
