# Generated by Django 3.0.4 on 2020-04-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor_app', '0007_add_insurance_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_claim_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inid', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('aid', models.CharField(max_length=100)),
                ('aname', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('license_num', models.CharField(max_length=100)),
            ],
        ),
    ]
