# Generated by Django 3.0.4 on 2020-04-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor_app', '0008_add_claim_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_claim_details',
            name='aname',
        ),
        migrations.RemoveField(
            model_name='add_claim_details',
            name='date',
        ),
        migrations.RemoveField(
            model_name='add_claim_details',
            name='license_num',
        ),
    ]
