# Generated by Django 3.0.4 on 2020-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor_app', '0009_auto_20200421_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='forward_claim_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inid', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('aid', models.CharField(max_length=100)),
            ],
        ),
    ]
