# Generated by Django 3.0.4 on 2020-05-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor_app', '0011_add_claim_details_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward_claim_details',
            name='image',
            field=models.FileField(default='SOME STRING', upload_to=''),
        ),
    ]
